Set default value of boresight_rotation_angle to 0
The previous default value for the boresight_rotation_angle,
float("nan"), was causing ingest attempts for raw images to fail with
the following error

    RuntimeError: Some failures encountered during ingestion

Hence, changed the default value to 0.0.